### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by oleg-pahl** [alexander-naumov/pam-accesscontrol#12]
**# TEST NEW SMTP FUNC**

> PRECONFIG:
```
* debian 9.7 (minimal server install) : just 120 pkg - without X11
$ wget -nv https://download.opensuse.org/repositories/home:Alexander_Naumov: 
   pam-accesscontrol/Debian_9.0/Release.key -O Release.key
$ apt-key add - < Release.key
$ apt-get update
$ echo 'deb http://download.opensuse.org/repositories/home:/Alexander_Naumov:
   /pam-accesscontrol/Debian_9.0/ /' > 
   /etc/apt/sources.list.d/home:Alexander_Naumov:pam-accesscontrol.list
$ apt install pam-accesscontrol
$ cd /tmp
$ git@github.com:alexander-naumov/pam-accesscontrol.git
```
> update with upstream
```
$ apt install mailutils
$ apt install postfix
```
>    type: local only
>    name: debian.fritz.box
```
$ systemctl restart postfix
$ CHECK: echo "TEST MAIL" | mail -s "Subject" root@localhost
$ vim pam-accessconfig.conf
```

> SERVER:127.0.0.1
> SSHD deface@posteo.de,deface@localhost,root@localhost,root@debian.fritz.box
```
RESULT:

+ CONFIG ----------------------------------- PASSWD OK -------- PASSWD NG -------+
|				                                                 |
| LOGIN (SSH) + SSH OPEN FOR USER .......... MAIL LOCAL -> OK	MAIL LOCAL -> NO?|
|	       				     MAIL EXTER -> NO? 	MAIL EXTER -> NO?|
|                                                                                |
| LOGIN (SSH) + SSH CLOSED FOR USER ........ MAIL LOCAL -> NO?	MAIL LOCAL -> NO?|	
|                                            MAIL EXTER -> NO? 	MAIL EXTER -> NO?|
+--------------------------------------------------------------------------------+
```

**Comment by oleg-pahl** [comment]
FYI

**Comment by alexander-naumov** [comment]
Well, the idea was to send notification mail **only** if someone logged in via specified PAM service.

In other words:
If you have CLOSE option and can't login, you have to receive no mail.
If you have OPEN option and type wrong password you also will have no mail.

That means that only "mail exter" looks like a bug for me. But the question is here how is configured DNS in your environment. Can you send "exter" mail in console by using mailx(1) like you showed in your test case?

**Comment by oleg-pahl** [comment]
ok. In process ..

**Comment by oleg-pahl** [comment]
Hi,

According info below its working correctly!
Many thx for your strong support.

> P.S. Its will take me a lot of time to check new feature pam-accesscontrol.
