### ISSUE TITLE
Build-Depends

### ISSUE THREAD

**Issue by oleg-pahl** [alexander-naumov/pam-accesscontrol#2]
Hi, Alex
Many Thx for your Support.
Could you be so kind to change _debian/control_ file and putt all Build-Depends in one line with comma or just put comma after config-package-dev!
Thx.

**Before:**

```
Build-Depends: debhelper (>= 7.0.50~),
 config-package-dev
 cdbs
```

**After:**

```
Build-Depends: debhelper (>= 7.0.50~), config-package-dev, cdbs
```

**Because of log from my GitLab CI/CD Docker Runner Container:**

> Running with gitlab-runner 11.0.0 (5396d320)
>   on MY Build Runner 92da1a5f
> Using Docker executor with image mybuildsys:latest ...
> Using locally found image version due to if-not-present pull policy
> Using docker image sha256:302d7f148f2d5a67bef8c075908bac1106431ba17ea2b09dffeb7184bcc9aadb for mybuildsys:latest ...
> Running on runner-92da1a5f-project-1-concurrent-0 via sietest...
> Cloning repository...
> Cloning into '/builds/root/pamac'...
> Checking out 87bbf50a as master...
> Skipping Git submodules setup
> $ dpkg-buildpackage -us -uc
> dpkg-buildpackage: source package pam-accesscontrol
> dpkg-buildpackage: source version 0.92
> dpkg-buildpackage: source distribution unstable
> dpkg-buildpackage: source changed by Alexander Naumov <alexander_naumov@opensuse.org>
> dpkg-buildpackage: host architecture amd64
> dpkg-source --before-build pamac
> dpkg-source: warning: can't parse dependency config-package-dev
> cdbs
> **dpkg-source: error: error occurred while parsing Build-Depends**
> dpkg-buildpackage: error: dpkg-source --before-build pamac gave error exit status 255
> ERROR: Job failed: exit code 1

**Comment by alexander-naumov** [comment]
Hi Oleg,
it's funny that GitLab doesn't parse it correctly, but... I fixed it for you anyway: https://github.com/alexander-naumov/pam-accesscontrol/commit/0df9376b0c11e56fc1ba99dbb118e028073a0f99

Have a lot of fun ;)

**Comment by alexander-naumov** [comment]
FIXED
