### ISSUE TITLE
pkg src name

### ISSUE THREAD

**Issue by FollowMeDown** [alexander-naumov/pam-accesscontrol#26]
Hi Alex,

could you be so kind to change src name from v0.97.tar.gz to goto-accesscontrol-0.97.tar.gz ?

Thx

**Comment by alexander-naumov** [comment]
> Hi Alex,
> 
> could you be so kind to change src name from v0.97.tar.gz to goto-accesscontrol-0.97.tar.gz ?
> 
> Thx

Well... is there any reason for that?
I can imagine that the next tarball's name will be pam-accesscontrol-0.98.tar.gz, but to change existing name is not the best idea: in OBS repository we have packages where v0.97.tar.gz is used.
On the other hand, you can just to fork this project and rename the release or create the new one, if you wish.

**Comment by FollowMeDown** [comment]
Becouse of ArchLiux BUILDPKG format =)

**Comment by alexander-naumov** [comment]
> Becouse of ArchLiux BUILDPKG format =)

I'm pretty sure you will find the solution/hack/workaround ;-)
