### ISSUE TITLE
Dep. problem -> openssh-server

### ISSUE THREAD

**Issue by oleg-pahl** [alexander-naumov/pam-accesscontrol#3]
Hi.
I try to build this app in my Docker Container with GitLab CI Runner.
I found that _opessh-server_ dep is absent.

_Workaround: Please fix **opessh-server** to **openssh-server**_

> Source: pam-accesscontrol
> Section: misc
> Standards-Version: 3.9.3
> Priority: extra
> Maintainer: Alexander Naumov <alexander_naumov@opensuse.org>
> Build-Depends: debhelper (>= 7.0.50~),
>  config-package-dev
>  cdbs
> 
> Package: pam-accesscontrol
> Pre-Depends: coreutils
> Architecture: any
> Depends: ${shlibs:Depends}, ${misc:Depends}, python (>= 2.7), **opessh-server,** libpam-python
> Description: PAM-ACCESSCONTROL is writen in python and use PAM to control login access to
>  the host via SSH, sddm, slim, gdm, kdm, xdm, lightdm, and login(1).
>  It makes it possible to manages access for some group of users or, for example,
>  depend on configuration can ask user for confirmation about establishing each
> new incoming SSH-connection.

**Comment by alexander-naumov** [comment]
Hi,
thanks a lot for testing!
Fix is there: https://github.com/alexander-naumov/pam-accesscontrol/commit/7794b4a13a2f17b6e4b6e67c5f7b6cbcf806a102
