### ISSUE TITLE
kcheckpass (kdm) -> ERROR -> /var/log/syslog 

### ISSUE THREAD

**Issue by oleg-pahl** [alexander-naumov/pam-accesscontrol#4]
Hi, Alex.

Its me.
look here ...

#### System: 

`ubuntu 14.04 (KDM) Kernel 4.4.0`

#### File:

`/lib/security/accesscontrol.py`
#### Code:
```python
def create_log(logtype, SERVICE, rhost, user, mode, msg):
  """
  It creates new entry in the logfile. The format of log-entry is:
  date <SPACE> current time <TAB> service name <TAB> rule <TAB> username@hostname <TAB> some_text <newline>
  """
  now  = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
  FILE = '/var/log/pam-accesscontrol-' + str(datetime.datetime.now().strftime("%Y-%m")) + '.log'

  if not rhost: rhost = "localhost"
  try:
    fd = open(FILE, 'a+')
    fd.write("%s%s%s%s%s\n" % (now.ljust(23), SERVICE.ljust(7), str(mode).ljust(10), (str(user) + "@" + str(rhost)).ljust(50), msg.ljust(15)))
    fd.close()
  except:
syslog.syslog(logtype + "Hi, I am here .... .... can't open/write logfile " + FILE)


```
#### Test:

I try lock my screen then unlock and check syslog

#### Syslog Output:

`# tail -f /var/log/syslog | grep filelog`
> date ... kcheckpass (kdm) ... can't open/write logfile /var/log/pam-accesscontrol ... 

#### Workaround:

```
# sudo chmod +s /path/kcheckpass 
or change func in file [accesscontrol.py]
```
#### Links:
https://github.com/KDE/kscreenlocker/tree/master/kcheckpass

Please contact me on deface@posteo.de if u need more info.
Many thx for your strong support!
**P.S. RunBSD**

**Comment by alexander-naumov** [comment]
Please provide version and configuration you use.
```
dpkg -l pam-accesscontrol
cat /etc/pam-accesscontrol/pam-accesscontro.conf
```
Thank you,
Alex

**Comment by alexander-naumov** [comment]
No reply for 2 weeks. Issue is closing as invalid.
